import { ButtonSignIn } from "@/components/button-sign-in";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { ShieldCheck } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen bg-zinc-50 font-sans dark:bg-zinc-950">
            <header className="flex px-6 py-4 bg-white border-b border-zinc-100 dark:bg-black dark:border-zinc-900 items-center">
              <div className="flex gap-2 text-xl font-bold dark:text-white">
                <ShieldCheck width={24} height={24} />
                <span>Sentinel Vault</span>
              </div>
              <div className="flex ml-auto gap-2">
                <ButtonSignIn />
                <ThemeToggle />
              </div>
            </header>
            <Toaster position="bottom-center" closeButton richColors />
            <main>{children}</main>
            <footer className="py-10 text-center text-zinc-600 border-t border-zinc-900">
              <p className="text-sm">
                © 2026 Sentinel Vault — Projet technique de Sukuna. Tout droit
                réservé.
              </p>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
